package com.revoola.firebaseModel

import com.revoola.databasefirebase.RLZoneDataSummery

data class RLSessionSummaryDataModel(
    val avgBurntCalories: Double?,
    val avgCadence: Double?,
    val avgHr: Double?,
    val avgPower: Int,
    val avgPowerFromDevice: Int,
    val avgRevPercentage: Double?,
    val avgSpeed: Double?,
    val avgSpeedForOneKm: Double?,
    val avgSpeedForOneMile: Double?,
    val burntCalories: Double?,
    val classDate: String,
    val classDescription: String,
    val classImage: String,
    val className: String,
    val classNote: String,
    val classType: String,
    val demsElevation: Int,
    val distance: Double?,
    val goal: String,
    val isClass: Boolean,
    val isPowerDeviceConnected: Boolean,
    val maxBurntCalories: Double?,
    val maxCadence: Double?,
    val maxHr: Int?,
    val maxPower: Int,
    val maxPowerFromDevice: Int,
    val maxRevPercentage: Double?,
    val maxSpeed: Double?,
    val maxSpeedForOneKm: Double?,
    val maxSpeedForOneMile: Double?,
    val minHr: Int?,
    val minRevPercentage: Double?,
    val remark: String,
    val revPercentage: Double?,
    val timestamp: Long,
    val totalElevation: Double?,
    val totalPower: Int,
    val totalRev: Double?,
    val totalSteps: Int?,
    val totalTime: Int,
    val typeOfGoal: String,
    val visibilityflagforthatsession: Int,
    val zone1: RLZoneDataSummery?,
    val zone2: RLZoneDataSummery?,
    val zone3: RLZoneDataSummery?,
    val zone4: RLZoneDataSummery?,
    val zone5: RLZoneDataSummery?,
    val zone6: RLZoneDataSummery?,
    val zone7: RLZoneDataSummery?
)

