package com.revoola.databasefirebase

object RevoolaKeys {

    const val  avgBurntCalories = "avgBurntCalories"
    const val  avgCadence = "avgCadence"
    const val avgHr = "avgHr"
    const val avgPower = "avgPower"
    const val avgPowerFromDevice = "avgPowerFromDevice"
    const val avgRevPercentage = "avgRevPercentage"
    const val avgSpeed = "avgSpeed"
    const val avgSpeedForOneKm = "avgSpeedForOneKm"
    const val avgSpeedForOneMile = "avgSpeedForOneMile"
    const val burntCalories = "burntCalories"
    const val classDate = "classDate"
    const val classImage = "classImage"
    const val className =  "className"
    const val classNote = "classNote"
    const val classType = "classType"
    const val distance = "distance"
    const val cadence = "cadence"
    const val connection = "connection"
    const val hr = "hr"
    const val power = "power"
    const val imageLinkSmall =  "imageLinkSmall"
    const val isClass = "isClass"
    const val isPowerDeviceConnected = "isPowerDeviceConnected"
    const val location = "location"
    const val maxBurntCalories = "maxBurntCalories"
    const val maxCadence = "maxCadence"
    const val maxHr = "maxHr"
    const val maxPower = "maxPower"
    const val maxPowerFromDevice = "maxPowerFromDevice"
    const val maxRevPercentage = "maxRevPercentage"
    const val maxSpeed = "maxSpeed"
    const val maxSpeedForOneKm = "maxSpeedForOneKm"
    const val maxSpeedForOneMile = "maxSpeedForOneMile"
    const val minHr = "minHr"
    const val minRevPercentage = "minRevPercentage"
    const val remark = "remark"
    const val speed = "speed"
    const val revPercentage = "revPercentage"
    const val rms = "rms"
    const val timestamp = "timestamp"
    const val totalElevation = "totalElevation"
    const val totalRev = "totalRev"
    const val totalTime = "totalTime"
    const val videoKey = "videoKey"
    const val visibilityflagforthatsession = "visibilityflagforthatsession"

    const val elevation = "elevation"
    const val data = "data"
    const val status = "status"
    const val gpxString = "gpxString"
    const val generatedDisntace = "generatedDisntace"
    const val generatedDisntace_T = "generatedDisntace_T"
    const val generatedElevation = "generatedElevation"
    const val generatedElevation_T = "generatedElevation_T"
    const val statusForElevationUpdate = "statusForElevationUpdate"
    const val elevationDic = "elevationDic"
    const val locationDic = "locationDic"
    const val speedDic = "speedDic"

    const val  Zone1 = "zone1"
    const val  Zone2 = "zone2"
    const val  Zone3 = "zone3"
    const val  Zone4 = "zone4"
    const val  Zone5 = "zone5"
    const val  Zone6 = "zone6"
    const val  Zone7 = "zone7"

    const val seconds = "seconds"

    const val arrBurntCalories = "arrBurntCalories"
    const val arrCadence = "arrCadence"
    const val arrCumDistance = "arrCumDistance"
    const val arrCumElevation = "arrCumElevation"
    const val arrCumSpeed = "arrCumSpeed"
    const val arrDistance = "arrDistance"
    const val arrElevation = "arrElevation"
    const val arrHRRecordedSecond = "arrHRRecordedSecond"
    const val arrHr = "arrHr"
    const val arrRevPercentage = "arrRevPercentage"
    const val arrRevSecond = "arrRevSecond"
    const val arrSpeed = "arrSpeed"
    const val speedForOneKm = "speedForOneKm"
    const val speedForOneMile = "speedForOneMile"

    const val maxHrUsedForCalculation = "maxHrUsedForCalculation"
    const val maxHrUsedForCalculation_Last = "maxHrUsedForCalculation_Last"
    const val restingHrUsedForCalculation = "restingHrUsedForCalculation"
    const val restingHrUsedForCalculation_Last = "restingHrUsedForCalculation_Last"
    const val classDescription = "classDescription"
    const val demsElevation = "demsElevation"
    const val goal = "goal"
    const val mapGeneratedUrl = "mapGeneratedUrl"
    const val totalPower = "totalPower"
    const val totalSteps = "totalSteps"
    const val typeOfGoal = "typeOfGoal"
    const val arrAvgCadence = "arrAvgCadence"
    const val arrAvgHr = "arrAvgHr"
    const val arrAvgPower = "arrAvgPower"
    const val arrAvgRevPercentage = "arrAvgRevPercentage"
    const val arrMaxCadence = "arrMaxCadence"
    const val arrMaxHr = "arrMaxHr"
    const val arrMaxPower = "arrMaxPower"
    const val arrMaxRevPercentage = "arrMaxRevPercentage"
    const val arrPower = "arrPower"
    const val arrPowerFromDevice = "arrPowerFromDevice"
    const val displayImage = "displayImage"
    const val displayName = "displayName"
    const val flagImage = "flagImage"
    const val flagName = "flagName"
    const val MaxHrUsedForCalculation = "maxHrUsedForCalculation"


    const val connectivity = "connectivity"
    const val deviceRecordedData = "deviceRecordedData"
    const val gpx = "gpx"
    const val gpx_T = "gpx_T"
    const val gpx_T_Server = "gpx_T_Server"
    const val gpx_T_Server_N = "gpx_T_Server_N"



            
}